### ISSUE TITLE
Use "returningQuery" function on Select / SelectOne Query

### ISSUE THREAD

**Issue by jdemangeon** [marmelab/postgres-queries#17]
Select query don't use "returningQuery" function as other queries. FInd for which reason and maybe fix it.

**Comment by ThieryMichel** [comment]
returningQuery is to generate the RETURNING part of a query.
Like with update:
```sql
UPDATE table SET col="value" WHERE id="id" RETURNING id, col;
```
Since it's not part of the select syntax, there is no reason for select and selectOne to use it.
