### ISSUE TITLE
Bad warning message while updating, it uses filter warning

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/postgres-queries#26]
Say I have the following code with a `character` table, some readable fields, and other writable fields:

```js
const { updateOne } = crud({
    table: 'character',
    writableCols: ['user_id', 'name', 'position'],
    returnCols: ['id', 'uuid', 'user_id', 'name', 'position'],
});
```
If I want to update a whole `character` object like:

```js
const character = {
    id: 42,
    uuid: 'uuid',
    user_id: 1,
    name: 'name',
    position: 'position',
    ...otherFields,
};

await client.namedQuery(updateOne(character.id, character));
```

I get the following warnings, because of the non-writable fields:

```
⚠  warning                      Ignoring filter: id. Allowed columns: user_id,name,position
⚠  warning                      Ignoring filter: uuid. Allowed columns: user_id,name,position
⚠  warning                      Ignoring filter: room. Allowed columns: user_id,name,position
⚠  warning                      Ignoring filter: avatar. Allowed columns: user_id,name,position
⚠  warning                      Ignoring filter: inventory. Allowed columns: user_id,name,position
```

I have several issues with this warning:

1. This is not **filters** but fields / columns.
2. It is better to ignore non-writable fields, or get a debug message (instead of a warning) in the case of an update. Have a warning in the select case is right.
3. It's better to batch the warning instead of a warn for each field. I extensively use update queries and this spam a lot in the console.
4. It lacks of context in this message.

I would suggest to replace this warning by a debug log for the update query, and in the case of the select  have a message more like:

> ⚠  postgres-queries                      The "select" query received non-filterable fields in parameter and ignored them: "id, uuid, room, ...". The available fields are: "..."

**Comment by ThieryMichel** [comment]
fixed in #27
